/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.11 Sat Oct 19 16:43:47 2024.
 */

#include <string.h>

#include "inverter_dbc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int inverter_dbc_rl_amk_actual_1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rl_amk_actual_1_t *src_p,
    size_t size)
{
    uint16_t rl_magnetizing_current;
    uint32_t rl_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_system_ready, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_error, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_warn, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_quit_dc_on, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_dc_on, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_quit_inverter_on, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_inverter_on, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_status_derating, 7u, 0x80u);
    rl_feedback_velocity = (uint32_t)src_p->rl_feedback_velocity;
    dst_p[2] |= pack_left_shift_u32(rl_feedback_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(rl_feedback_velocity, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(rl_feedback_velocity, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(rl_feedback_velocity, 24u, 0xffu);
    rl_magnetizing_current = (uint16_t)src_p->rl_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(rl_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rl_magnetizing_current, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rl_amk_actual_1_unpack(
    struct inverter_dbc_rl_amk_actual_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rl_magnetizing_current;
    uint32_t rl_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rl_status_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->rl_status_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->rl_status_warn = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->rl_status_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->rl_status_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->rl_status_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->rl_status_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->rl_status_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    rl_feedback_velocity = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    rl_feedback_velocity |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    rl_feedback_velocity |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    rl_feedback_velocity |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->rl_feedback_velocity = (int32_t)rl_feedback_velocity;
    rl_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rl_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rl_magnetizing_current = (int16_t)rl_magnetizing_current;

    return (0);
}

int inverter_dbc_rl_amk_actual_1_init(struct inverter_dbc_rl_amk_actual_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rl_amk_actual_1_t));

    return 0;
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_system_ready_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_system_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_system_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_error_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_error_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_warn_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_warn_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_warn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_quit_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_quit_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_quit_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_quit_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_quit_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_quit_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_actual_1_rl_status_derating_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_status_derating_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_status_derating_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int32_t inverter_dbc_rl_amk_actual_1_rl_feedback_velocity_encode(double value)
{
    return (int32_t)(value / 0.0001);
}

double inverter_dbc_rl_amk_actual_1_rl_feedback_velocity_decode(int32_t value)
{
    return ((double)value * 0.0001);
}

bool inverter_dbc_rl_amk_actual_1_rl_feedback_velocity_is_in_range(int32_t value)
{
    return ((value >= -1000000000) && (value <= 1000000000));
}

int16_t inverter_dbc_rl_amk_actual_1_rl_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double inverter_dbc_rl_amk_actual_1_rl_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_1_rl_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_rl_amk_actual_2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rl_amk_actual_2_t *src_p,
    size_t size)
{
    uint16_t rl_temp_igbt;
    uint16_t rl_temp_inverter;
    uint16_t rl_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    rl_temp_motor = (uint16_t)src_p->rl_temp_motor;
    dst_p[0] |= pack_left_shift_u16(rl_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(rl_temp_motor, 8u, 0xffu);
    rl_temp_inverter = (uint16_t)src_p->rl_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(rl_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(rl_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->rl_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->rl_error_info, 8u, 0xffu);
    rl_temp_igbt = (uint16_t)src_p->rl_temp_igbt;
    dst_p[6] |= pack_left_shift_u16(rl_temp_igbt, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rl_temp_igbt, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rl_amk_actual_2_unpack(
    struct inverter_dbc_rl_amk_actual_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rl_temp_igbt;
    uint16_t rl_temp_inverter;
    uint16_t rl_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    rl_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    rl_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rl_temp_motor = (int16_t)rl_temp_motor;
    rl_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    rl_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rl_temp_inverter = (int16_t)rl_temp_inverter;
    dst_p->rl_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->rl_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    rl_temp_igbt = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rl_temp_igbt |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rl_temp_igbt = (int16_t)rl_temp_igbt;

    return (0);
}

int inverter_dbc_rl_amk_actual_2_init(struct inverter_dbc_rl_amk_actual_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rl_amk_actual_2_t));

    return 0;
}

int16_t inverter_dbc_rl_amk_actual_2_rl_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rl_amk_actual_2_rl_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rl_amk_actual_2_rl_temp_motor_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_dbc_rl_amk_actual_2_rl_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rl_amk_actual_2_rl_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rl_amk_actual_2_rl_temp_inverter_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t inverter_dbc_rl_amk_actual_2_rl_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_rl_amk_actual_2_rl_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_actual_2_rl_error_info_is_in_range(uint16_t value)
{
    return (value <= 3277u);
}

int16_t inverter_dbc_rl_amk_actual_2_rl_temp_igbt_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rl_amk_actual_2_rl_temp_igbt_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rl_amk_actual_2_rl_temp_igbt_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_rl_amk_rit_set1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rl_amk_rit_set1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->rl_erro_r_list1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->rl_erro_r_list1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->rl_erro_r_list1, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->rl_erro_r_list1, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->rl_erro_r_list2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->rl_erro_r_list2, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->rl_erro_r_list2, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->rl_erro_r_list2, 24u, 0xffu);

    return (8);
}

int inverter_dbc_rl_amk_rit_set1_unpack(
    struct inverter_dbc_rl_amk_rit_set1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rl_erro_r_list1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->rl_erro_r_list1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->rl_erro_r_list1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->rl_erro_r_list1 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->rl_erro_r_list2 = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->rl_erro_r_list2 |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->rl_erro_r_list2 |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->rl_erro_r_list2 |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int inverter_dbc_rl_amk_rit_set1_init(struct inverter_dbc_rl_amk_rit_set1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rl_amk_rit_set1_t));

    return 0;
}

uint32_t inverter_dbc_rl_amk_rit_set1_rl_erro_r_list1_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_rl_amk_rit_set1_rl_erro_r_list1_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_rit_set1_rl_erro_r_list1_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint32_t inverter_dbc_rl_amk_rit_set1_rl_erro_r_list2_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_rl_amk_rit_set1_rl_erro_r_list2_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_rit_set1_rl_erro_r_list2_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

int inverter_dbc_rl_amk_rit_set2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rl_amk_rit_set2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->rl_error_list3, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->rl_error_list3, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->rl_error_list3, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->rl_error_list3, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->rl_dc_bus_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->rl_dc_bus_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->rl_dc_bus_voltage_monitoring, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->rl_dc_bus_voltage_monitoring, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rl_amk_rit_set2_unpack(
    struct inverter_dbc_rl_amk_rit_set2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rl_error_list3 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->rl_error_list3 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->rl_error_list3 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->rl_error_list3 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->rl_dc_bus_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->rl_dc_bus_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->rl_dc_bus_voltage_monitoring = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->rl_dc_bus_voltage_monitoring |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int inverter_dbc_rl_amk_rit_set2_init(struct inverter_dbc_rl_amk_rit_set2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rl_amk_rit_set2_t));

    return 0;
}

uint32_t inverter_dbc_rl_amk_rit_set2_rl_error_list3_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_rl_amk_rit_set2_rl_error_list3_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_rit_set2_rl_error_list3_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint16_t inverter_dbc_rl_amk_rit_set2_rl_dc_bus_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_rl_amk_rit_set2_rl_dc_bus_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_rit_set2_rl_dc_bus_voltage_is_in_range(uint16_t value)
{
    return (value <= 4096u);
}

uint16_t inverter_dbc_rl_amk_rit_set2_rl_dc_bus_voltage_monitoring_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double inverter_dbc_rl_amk_rit_set2_rl_dc_bus_voltage_monitoring_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rl_amk_rit_set2_rl_dc_bus_voltage_monitoring_is_in_range(uint16_t value)
{
    return (value <= 40960u);
}

int inverter_dbc_rl_amk_setpoints_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rl_amk_setpoints_t *src_p,
    size_t size)
{
    uint16_t rl_amk_torque_limit_negative;
    uint16_t rl_amk_torque_limit_positive;
    uint16_t rl_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->rl_amk_b_inverter_on, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_amk_b_dc_on, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_amk_b_enable, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->rl_amk_b_error_reset, 3u, 0x08u);
    rl_amk_torque_setpoint = (uint16_t)src_p->rl_amk_torque_setpoint;
    dst_p[2] |= pack_left_shift_u16(rl_amk_torque_setpoint, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(rl_amk_torque_setpoint, 8u, 0xffu);
    rl_amk_torque_limit_positive = (uint16_t)src_p->rl_amk_torque_limit_positive;
    dst_p[4] |= pack_left_shift_u16(rl_amk_torque_limit_positive, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(rl_amk_torque_limit_positive, 8u, 0xffu);
    rl_amk_torque_limit_negative = (uint16_t)src_p->rl_amk_torque_limit_negative;
    dst_p[6] |= pack_left_shift_u16(rl_amk_torque_limit_negative, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rl_amk_torque_limit_negative, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rl_amk_setpoints_unpack(
    struct inverter_dbc_rl_amk_setpoints_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rl_amk_torque_limit_negative;
    uint16_t rl_amk_torque_limit_positive;
    uint16_t rl_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rl_amk_b_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->rl_amk_b_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->rl_amk_b_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->rl_amk_b_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    rl_amk_torque_setpoint = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    rl_amk_torque_setpoint |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rl_amk_torque_setpoint = (int16_t)rl_amk_torque_setpoint;
    rl_amk_torque_limit_positive = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    rl_amk_torque_limit_positive |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->rl_amk_torque_limit_positive = (int16_t)rl_amk_torque_limit_positive;
    rl_amk_torque_limit_negative = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rl_amk_torque_limit_negative |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rl_amk_torque_limit_negative = (int16_t)rl_amk_torque_limit_negative;

    return (0);
}

int inverter_dbc_rl_amk_setpoints_init(struct inverter_dbc_rl_amk_setpoints_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rl_amk_setpoints_t));

    return 0;
}

uint8_t inverter_dbc_rl_amk_setpoints_rl_amk_b_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_setpoints_rl_amk_b_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_setpoints_rl_amk_b_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_setpoints_rl_amk_b_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_setpoints_rl_amk_b_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_setpoints_rl_amk_b_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_setpoints_rl_amk_b_enable_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_setpoints_rl_amk_b_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_setpoints_rl_amk_b_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rl_amk_setpoints_rl_amk_b_error_reset_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rl_amk_setpoints_rl_amk_b_error_reset_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rl_amk_setpoints_rl_amk_b_error_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t inverter_dbc_rl_amk_setpoints_rl_amk_torque_setpoint_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rl_amk_setpoints_rl_amk_torque_setpoint_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rl_amk_setpoints_rl_amk_torque_setpoint_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 10000));
}

int16_t inverter_dbc_rl_amk_setpoints_rl_amk_torque_limit_positive_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rl_amk_setpoints_rl_amk_torque_limit_positive_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rl_amk_setpoints_rl_amk_torque_limit_positive_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t inverter_dbc_rl_amk_setpoints_rl_amk_torque_limit_negative_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rl_amk_setpoints_rl_amk_torque_limit_negative_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rl_amk_setpoints_rl_amk_torque_limit_negative_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int inverter_dbc_rr_amk_actual_1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rr_amk_actual_1_t *src_p,
    size_t size)
{
    uint16_t rr_magnetizing_current;
    uint32_t rr_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_system_ready, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_error, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_warn, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_quit_dc_on, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_dc_on, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_quit_inverter_on, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_inverter_on, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_status_derating, 7u, 0x80u);
    rr_feedback_velocity = (uint32_t)src_p->rr_feedback_velocity;
    dst_p[2] |= pack_left_shift_u32(rr_feedback_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(rr_feedback_velocity, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(rr_feedback_velocity, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(rr_feedback_velocity, 24u, 0xffu);
    rr_magnetizing_current = (uint16_t)src_p->rr_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(rr_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rr_magnetizing_current, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rr_amk_actual_1_unpack(
    struct inverter_dbc_rr_amk_actual_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rr_magnetizing_current;
    uint32_t rr_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_status_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->rr_status_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->rr_status_warn = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->rr_status_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->rr_status_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->rr_status_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->rr_status_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->rr_status_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    rr_feedback_velocity = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    rr_feedback_velocity |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    rr_feedback_velocity |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    rr_feedback_velocity |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->rr_feedback_velocity = (int32_t)rr_feedback_velocity;
    rr_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rr_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rr_magnetizing_current = (int16_t)rr_magnetizing_current;

    return (0);
}

int inverter_dbc_rr_amk_actual_1_init(struct inverter_dbc_rr_amk_actual_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rr_amk_actual_1_t));

    return 0;
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_system_ready_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_system_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_system_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_error_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_error_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_warn_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_warn_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_warn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_quit_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_quit_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_quit_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_quit_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_quit_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_quit_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_actual_1_rr_status_derating_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_status_derating_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_status_derating_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int32_t inverter_dbc_rr_amk_actual_1_rr_feedback_velocity_encode(double value)
{
    return (int32_t)(value / 0.0001);
}

double inverter_dbc_rr_amk_actual_1_rr_feedback_velocity_decode(int32_t value)
{
    return ((double)value * 0.0001);
}

bool inverter_dbc_rr_amk_actual_1_rr_feedback_velocity_is_in_range(int32_t value)
{
    return ((value >= -1000000000) && (value <= 1000000000));
}

int16_t inverter_dbc_rr_amk_actual_1_rr_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double inverter_dbc_rr_amk_actual_1_rr_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_1_rr_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_rr_amk_actual_2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rr_amk_actual_2_t *src_p,
    size_t size)
{
    uint16_t rr_temp_igbt;
    uint16_t rr_temp_inverter;
    uint16_t rr_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    rr_temp_motor = (uint16_t)src_p->rr_temp_motor;
    dst_p[0] |= pack_left_shift_u16(rr_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(rr_temp_motor, 8u, 0xffu);
    rr_temp_inverter = (uint16_t)src_p->rr_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(rr_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(rr_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->rr_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->rr_error_info, 8u, 0xffu);
    rr_temp_igbt = (uint16_t)src_p->rr_temp_igbt;
    dst_p[6] |= pack_left_shift_u16(rr_temp_igbt, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rr_temp_igbt, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rr_amk_actual_2_unpack(
    struct inverter_dbc_rr_amk_actual_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rr_temp_igbt;
    uint16_t rr_temp_inverter;
    uint16_t rr_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    rr_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    rr_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->rr_temp_motor = (int16_t)rr_temp_motor;
    rr_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    rr_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rr_temp_inverter = (int16_t)rr_temp_inverter;
    dst_p->rr_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->rr_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    rr_temp_igbt = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rr_temp_igbt |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rr_temp_igbt = (int16_t)rr_temp_igbt;

    return (0);
}

int inverter_dbc_rr_amk_actual_2_init(struct inverter_dbc_rr_amk_actual_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rr_amk_actual_2_t));

    return 0;
}

int16_t inverter_dbc_rr_amk_actual_2_rr_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rr_amk_actual_2_rr_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rr_amk_actual_2_rr_temp_motor_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_dbc_rr_amk_actual_2_rr_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rr_amk_actual_2_rr_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rr_amk_actual_2_rr_temp_inverter_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t inverter_dbc_rr_amk_actual_2_rr_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_rr_amk_actual_2_rr_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_actual_2_rr_error_info_is_in_range(uint16_t value)
{
    return (value <= 3277u);
}

int16_t inverter_dbc_rr_amk_actual_2_rr_temp_igbt_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rr_amk_actual_2_rr_temp_igbt_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rr_amk_actual_2_rr_temp_igbt_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_rr_amk_rit_set1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rr_amk_rit_set1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->rr_errorlist1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->rr_errorlist1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->rr_errorlist1, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->rr_errorlist1, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->rr_errorlist2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->rr_errorlist2, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->rr_errorlist2, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->rr_errorlist2, 24u, 0xffu);

    return (8);
}

int inverter_dbc_rr_amk_rit_set1_unpack(
    struct inverter_dbc_rr_amk_rit_set1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_errorlist1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->rr_errorlist1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->rr_errorlist1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->rr_errorlist1 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->rr_errorlist2 = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->rr_errorlist2 |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->rr_errorlist2 |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->rr_errorlist2 |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int inverter_dbc_rr_amk_rit_set1_init(struct inverter_dbc_rr_amk_rit_set1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rr_amk_rit_set1_t));

    return 0;
}

uint32_t inverter_dbc_rr_amk_rit_set1_rr_errorlist1_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_rr_amk_rit_set1_rr_errorlist1_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_rit_set1_rr_errorlist1_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint32_t inverter_dbc_rr_amk_rit_set1_rr_errorlist2_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_rr_amk_rit_set1_rr_errorlist2_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_rit_set1_rr_errorlist2_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

int inverter_dbc_rr_amk_rit_set2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rr_amk_rit_set2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->rr_errorlist3, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->rr_errorlist3, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->rr_errorlist3, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->rr_errorlist3, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->rr_dc_bus_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->rr_dc_bus_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->rr_dc_bus_voltage_monitoring, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->rr_dc_bus_voltage_monitoring, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rr_amk_rit_set2_unpack(
    struct inverter_dbc_rr_amk_rit_set2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_errorlist3 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->rr_errorlist3 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->rr_errorlist3 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->rr_errorlist3 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->rr_dc_bus_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->rr_dc_bus_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->rr_dc_bus_voltage_monitoring = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->rr_dc_bus_voltage_monitoring |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int inverter_dbc_rr_amk_rit_set2_init(struct inverter_dbc_rr_amk_rit_set2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rr_amk_rit_set2_t));

    return 0;
}

uint32_t inverter_dbc_rr_amk_rit_set2_rr_errorlist3_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_rr_amk_rit_set2_rr_errorlist3_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_rit_set2_rr_errorlist3_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint16_t inverter_dbc_rr_amk_rit_set2_rr_dc_bus_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_rr_amk_rit_set2_rr_dc_bus_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_rit_set2_rr_dc_bus_voltage_is_in_range(uint16_t value)
{
    return (value <= 4096u);
}

uint16_t inverter_dbc_rr_amk_rit_set2_rr_dc_bus_voltage_monitoring_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double inverter_dbc_rr_amk_rit_set2_rr_dc_bus_voltage_monitoring_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rr_amk_rit_set2_rr_dc_bus_voltage_monitoring_is_in_range(uint16_t value)
{
    return (value <= 40960u);
}

int inverter_dbc_rr_amk_setpoints_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_rr_amk_setpoints_t *src_p,
    size_t size)
{
    uint16_t rr_amk_torque_limit_negative;
    uint16_t rr_amk_torque_limit_positive;
    uint16_t rr_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->rr_amk_b_inverter_on, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_amk_b_dc_on, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_amk_b_enable, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->rr_amk_b_error_reset, 3u, 0x08u);
    rr_amk_torque_setpoint = (uint16_t)src_p->rr_amk_torque_setpoint;
    dst_p[2] |= pack_left_shift_u16(rr_amk_torque_setpoint, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(rr_amk_torque_setpoint, 8u, 0xffu);
    rr_amk_torque_limit_positive = (uint16_t)src_p->rr_amk_torque_limit_positive;
    dst_p[4] |= pack_left_shift_u16(rr_amk_torque_limit_positive, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(rr_amk_torque_limit_positive, 8u, 0xffu);
    rr_amk_torque_limit_negative = (uint16_t)src_p->rr_amk_torque_limit_negative;
    dst_p[6] |= pack_left_shift_u16(rr_amk_torque_limit_negative, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(rr_amk_torque_limit_negative, 8u, 0xffu);

    return (8);
}

int inverter_dbc_rr_amk_setpoints_unpack(
    struct inverter_dbc_rr_amk_setpoints_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t rr_amk_torque_limit_negative;
    uint16_t rr_amk_torque_limit_positive;
    uint16_t rr_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rr_amk_b_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->rr_amk_b_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->rr_amk_b_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->rr_amk_b_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    rr_amk_torque_setpoint = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    rr_amk_torque_setpoint |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rr_amk_torque_setpoint = (int16_t)rr_amk_torque_setpoint;
    rr_amk_torque_limit_positive = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    rr_amk_torque_limit_positive |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->rr_amk_torque_limit_positive = (int16_t)rr_amk_torque_limit_positive;
    rr_amk_torque_limit_negative = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    rr_amk_torque_limit_negative |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->rr_amk_torque_limit_negative = (int16_t)rr_amk_torque_limit_negative;

    return (0);
}

int inverter_dbc_rr_amk_setpoints_init(struct inverter_dbc_rr_amk_setpoints_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_rr_amk_setpoints_t));

    return 0;
}

uint8_t inverter_dbc_rr_amk_setpoints_rr_amk_b_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_setpoints_rr_amk_b_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_setpoints_rr_amk_b_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_setpoints_rr_amk_b_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_setpoints_rr_amk_b_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_setpoints_rr_amk_b_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_setpoints_rr_amk_b_enable_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_setpoints_rr_amk_b_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_setpoints_rr_amk_b_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_rr_amk_setpoints_rr_amk_b_error_reset_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_rr_amk_setpoints_rr_amk_b_error_reset_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_rr_amk_setpoints_rr_amk_b_error_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t inverter_dbc_rr_amk_setpoints_rr_amk_torque_setpoint_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rr_amk_setpoints_rr_amk_torque_setpoint_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rr_amk_setpoints_rr_amk_torque_setpoint_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 10000));
}

int16_t inverter_dbc_rr_amk_setpoints_rr_amk_torque_limit_positive_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rr_amk_setpoints_rr_amk_torque_limit_positive_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rr_amk_setpoints_rr_amk_torque_limit_positive_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t inverter_dbc_rr_amk_setpoints_rr_amk_torque_limit_negative_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_rr_amk_setpoints_rr_amk_torque_limit_negative_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_rr_amk_setpoints_rr_amk_torque_limit_negative_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int inverter_dbc_fl_amk_actual_1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fl_amk_actual_1_t *src_p,
    size_t size)
{
    uint16_t fl_magnetizing_current;
    uint32_t fl_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_system_ready, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_error, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_warn, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_quit_dc_on, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_dc_on, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_quit_inverter_on, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_inverter_on, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_status_derating, 7u, 0x80u);
    fl_feedback_velocity = (uint32_t)src_p->fl_feedback_velocity;
    dst_p[2] |= pack_left_shift_u32(fl_feedback_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(fl_feedback_velocity, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(fl_feedback_velocity, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(fl_feedback_velocity, 24u, 0xffu);
    fl_magnetizing_current = (uint16_t)src_p->fl_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(fl_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fl_magnetizing_current, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fl_amk_actual_1_unpack(
    struct inverter_dbc_fl_amk_actual_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fl_magnetizing_current;
    uint32_t fl_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fl_status_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->fl_status_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->fl_status_warn = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->fl_status_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->fl_status_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->fl_status_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->fl_status_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->fl_status_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    fl_feedback_velocity = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    fl_feedback_velocity |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    fl_feedback_velocity |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    fl_feedback_velocity |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->fl_feedback_velocity = (int32_t)fl_feedback_velocity;
    fl_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fl_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fl_magnetizing_current = (int16_t)fl_magnetizing_current;

    return (0);
}

int inverter_dbc_fl_amk_actual_1_init(struct inverter_dbc_fl_amk_actual_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fl_amk_actual_1_t));

    return 0;
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_system_ready_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_system_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_system_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_error_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_error_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_warn_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_warn_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_warn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_quit_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_quit_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_quit_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_quit_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_quit_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_quit_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_actual_1_fl_status_derating_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_status_derating_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_status_derating_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int32_t inverter_dbc_fl_amk_actual_1_fl_feedback_velocity_encode(double value)
{
    return (int32_t)(value / 0.0001);
}

double inverter_dbc_fl_amk_actual_1_fl_feedback_velocity_decode(int32_t value)
{
    return ((double)value * 0.0001);
}

bool inverter_dbc_fl_amk_actual_1_fl_feedback_velocity_is_in_range(int32_t value)
{
    return ((value >= -1000000000) && (value <= 1000000000));
}

int16_t inverter_dbc_fl_amk_actual_1_fl_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double inverter_dbc_fl_amk_actual_1_fl_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_1_fl_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_fl_amk_actual_2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fl_amk_actual_2_t *src_p,
    size_t size)
{
    uint16_t fl_temp_igbt;
    uint16_t fl_temp_inverter;
    uint16_t fl_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    fl_temp_motor = (uint16_t)src_p->fl_temp_motor;
    dst_p[0] |= pack_left_shift_u16(fl_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(fl_temp_motor, 8u, 0xffu);
    fl_temp_inverter = (uint16_t)src_p->fl_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(fl_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(fl_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->fl_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->fl_error_info, 8u, 0xffu);
    fl_temp_igbt = (uint16_t)src_p->fl_temp_igbt;
    dst_p[6] |= pack_left_shift_u16(fl_temp_igbt, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fl_temp_igbt, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fl_amk_actual_2_unpack(
    struct inverter_dbc_fl_amk_actual_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fl_temp_igbt;
    uint16_t fl_temp_inverter;
    uint16_t fl_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    fl_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    fl_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->fl_temp_motor = (int16_t)fl_temp_motor;
    fl_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    fl_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fl_temp_inverter = (int16_t)fl_temp_inverter;
    dst_p->fl_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->fl_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    fl_temp_igbt = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fl_temp_igbt |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fl_temp_igbt = (int16_t)fl_temp_igbt;

    return (0);
}

int inverter_dbc_fl_amk_actual_2_init(struct inverter_dbc_fl_amk_actual_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fl_amk_actual_2_t));

    return 0;
}

int16_t inverter_dbc_fl_amk_actual_2_fl_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fl_amk_actual_2_fl_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fl_amk_actual_2_fl_temp_motor_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_dbc_fl_amk_actual_2_fl_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fl_amk_actual_2_fl_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fl_amk_actual_2_fl_temp_inverter_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t inverter_dbc_fl_amk_actual_2_fl_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_fl_amk_actual_2_fl_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_actual_2_fl_error_info_is_in_range(uint16_t value)
{
    return (value <= 3277u);
}

int16_t inverter_dbc_fl_amk_actual_2_fl_temp_igbt_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fl_amk_actual_2_fl_temp_igbt_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fl_amk_actual_2_fl_temp_igbt_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_fl_amk_rit_set1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fl_amk_rit_set1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->fl_errorlist1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->fl_errorlist1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->fl_errorlist1, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->fl_errorlist1, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->fl_errorlist2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->fl_errorlist2, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->fl_errorlist2, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->fl_errorlist2, 24u, 0xffu);

    return (8);
}

int inverter_dbc_fl_amk_rit_set1_unpack(
    struct inverter_dbc_fl_amk_rit_set1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fl_errorlist1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->fl_errorlist1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->fl_errorlist1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->fl_errorlist1 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->fl_errorlist2 = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->fl_errorlist2 |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->fl_errorlist2 |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->fl_errorlist2 |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int inverter_dbc_fl_amk_rit_set1_init(struct inverter_dbc_fl_amk_rit_set1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fl_amk_rit_set1_t));

    return 0;
}

uint32_t inverter_dbc_fl_amk_rit_set1_fl_errorlist1_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_fl_amk_rit_set1_fl_errorlist1_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_rit_set1_fl_errorlist1_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint32_t inverter_dbc_fl_amk_rit_set1_fl_errorlist2_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_fl_amk_rit_set1_fl_errorlist2_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_rit_set1_fl_errorlist2_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

int inverter_dbc_fl_amk_rit_set2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fl_amk_rit_set2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->fl_error_list3, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->fl_error_list3, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->fl_error_list3, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->fl_error_list3, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->fl_dc_bus_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->fl_dc_bus_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->fl_dc_bus_voltage_monitoring, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->fl_dc_bus_voltage_monitoring, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fl_amk_rit_set2_unpack(
    struct inverter_dbc_fl_amk_rit_set2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fl_error_list3 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->fl_error_list3 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->fl_error_list3 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->fl_error_list3 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->fl_dc_bus_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->fl_dc_bus_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fl_dc_bus_voltage_monitoring = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->fl_dc_bus_voltage_monitoring |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int inverter_dbc_fl_amk_rit_set2_init(struct inverter_dbc_fl_amk_rit_set2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fl_amk_rit_set2_t));

    return 0;
}

uint32_t inverter_dbc_fl_amk_rit_set2_fl_error_list3_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_fl_amk_rit_set2_fl_error_list3_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_rit_set2_fl_error_list3_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint16_t inverter_dbc_fl_amk_rit_set2_fl_dc_bus_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_fl_amk_rit_set2_fl_dc_bus_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_rit_set2_fl_dc_bus_voltage_is_in_range(uint16_t value)
{
    return (value <= 4096u);
}

uint16_t inverter_dbc_fl_amk_rit_set2_fl_dc_bus_voltage_monitoring_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double inverter_dbc_fl_amk_rit_set2_fl_dc_bus_voltage_monitoring_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fl_amk_rit_set2_fl_dc_bus_voltage_monitoring_is_in_range(uint16_t value)
{
    return (value <= 40960u);
}

int inverter_dbc_fl_amk_setpoints_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fl_amk_setpoints_t *src_p,
    size_t size)
{
    uint16_t fl_amk_torque_limit_negative;
    uint16_t fl_amk_torque_limit_positive;
    uint16_t fl_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->fl_amk_b_inverter_on, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_amk_b_dc_on, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_amk_b_enable, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->fl_amk_b_error_reset, 3u, 0x08u);
    fl_amk_torque_setpoint = (uint16_t)src_p->fl_amk_torque_setpoint;
    dst_p[2] |= pack_left_shift_u16(fl_amk_torque_setpoint, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(fl_amk_torque_setpoint, 8u, 0xffu);
    fl_amk_torque_limit_positive = (uint16_t)src_p->fl_amk_torque_limit_positive;
    dst_p[4] |= pack_left_shift_u16(fl_amk_torque_limit_positive, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(fl_amk_torque_limit_positive, 8u, 0xffu);
    fl_amk_torque_limit_negative = (uint16_t)src_p->fl_amk_torque_limit_negative;
    dst_p[6] |= pack_left_shift_u16(fl_amk_torque_limit_negative, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fl_amk_torque_limit_negative, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fl_amk_setpoints_unpack(
    struct inverter_dbc_fl_amk_setpoints_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fl_amk_torque_limit_negative;
    uint16_t fl_amk_torque_limit_positive;
    uint16_t fl_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fl_amk_b_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->fl_amk_b_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->fl_amk_b_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->fl_amk_b_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    fl_amk_torque_setpoint = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    fl_amk_torque_setpoint |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fl_amk_torque_setpoint = (int16_t)fl_amk_torque_setpoint;
    fl_amk_torque_limit_positive = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    fl_amk_torque_limit_positive |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fl_amk_torque_limit_positive = (int16_t)fl_amk_torque_limit_positive;
    fl_amk_torque_limit_negative = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fl_amk_torque_limit_negative |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fl_amk_torque_limit_negative = (int16_t)fl_amk_torque_limit_negative;

    return (0);
}

int inverter_dbc_fl_amk_setpoints_init(struct inverter_dbc_fl_amk_setpoints_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fl_amk_setpoints_t));

    return 0;
}

uint8_t inverter_dbc_fl_amk_setpoints_fl_amk_b_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_setpoints_fl_amk_b_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_setpoints_fl_amk_b_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_setpoints_fl_amk_b_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_setpoints_fl_amk_b_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_setpoints_fl_amk_b_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_setpoints_fl_amk_b_enable_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_setpoints_fl_amk_b_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_setpoints_fl_amk_b_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fl_amk_setpoints_fl_amk_b_error_reset_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fl_amk_setpoints_fl_amk_b_error_reset_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fl_amk_setpoints_fl_amk_b_error_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t inverter_dbc_fl_amk_setpoints_fl_amk_torque_setpoint_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fl_amk_setpoints_fl_amk_torque_setpoint_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fl_amk_setpoints_fl_amk_torque_setpoint_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 10000));
}

int16_t inverter_dbc_fl_amk_setpoints_fl_amk_torque_limit_positive_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fl_amk_setpoints_fl_amk_torque_limit_positive_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fl_amk_setpoints_fl_amk_torque_limit_positive_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t inverter_dbc_fl_amk_setpoints_fl_amk_torque_limit_negative_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fl_amk_setpoints_fl_amk_torque_limit_negative_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fl_amk_setpoints_fl_amk_torque_limit_negative_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int inverter_dbc_fr_amk_actual_1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fr_amk_actual_1_t *src_p,
    size_t size)
{
    uint16_t fr_magnetizing_current;
    uint32_t fr_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_system_ready, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_error, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_warn, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_quit_dc_on, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_dc_on, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_quit_inverter_on, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_inverter_on, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_status_derating, 7u, 0x80u);
    fr_feedback_velocity = (uint32_t)src_p->fr_feedback_velocity;
    dst_p[2] |= pack_left_shift_u32(fr_feedback_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(fr_feedback_velocity, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(fr_feedback_velocity, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(fr_feedback_velocity, 24u, 0xffu);
    fr_magnetizing_current = (uint16_t)src_p->fr_magnetizing_current;
    dst_p[6] |= pack_left_shift_u16(fr_magnetizing_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fr_magnetizing_current, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fr_amk_actual_1_unpack(
    struct inverter_dbc_fr_amk_actual_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fr_magnetizing_current;
    uint32_t fr_feedback_velocity;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fr_status_system_ready = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->fr_status_error = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->fr_status_warn = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->fr_status_quit_dc_on = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->fr_status_dc_on = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->fr_status_quit_inverter_on = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->fr_status_inverter_on = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->fr_status_derating = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    fr_feedback_velocity = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    fr_feedback_velocity |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    fr_feedback_velocity |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    fr_feedback_velocity |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->fr_feedback_velocity = (int32_t)fr_feedback_velocity;
    fr_magnetizing_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fr_magnetizing_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fr_magnetizing_current = (int16_t)fr_magnetizing_current;

    return (0);
}

int inverter_dbc_fr_amk_actual_1_init(struct inverter_dbc_fr_amk_actual_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fr_amk_actual_1_t));

    return 0;
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_system_ready_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_system_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_system_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_error_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_error_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_warn_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_warn_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_warn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_quit_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_quit_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_quit_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_quit_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_quit_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_quit_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_actual_1_fr_status_derating_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_status_derating_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_status_derating_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int32_t inverter_dbc_fr_amk_actual_1_fr_feedback_velocity_encode(double value)
{
    return (int32_t)(value / 0.0001);
}

double inverter_dbc_fr_amk_actual_1_fr_feedback_velocity_decode(int32_t value)
{
    return ((double)value * 0.0001);
}

bool inverter_dbc_fr_amk_actual_1_fr_feedback_velocity_is_in_range(int32_t value)
{
    return ((value >= -1000000000) && (value <= 1000000000));
}

int16_t inverter_dbc_fr_amk_actual_1_fr_magnetizing_current_encode(double value)
{
    return (int16_t)(value);
}

double inverter_dbc_fr_amk_actual_1_fr_magnetizing_current_decode(int16_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_1_fr_magnetizing_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_fr_amk_actual_2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fr_amk_actual_2_t *src_p,
    size_t size)
{
    uint16_t fr_temp_igbt;
    uint16_t fr_temp_inverter;
    uint16_t fr_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    fr_temp_motor = (uint16_t)src_p->fr_temp_motor;
    dst_p[0] |= pack_left_shift_u16(fr_temp_motor, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(fr_temp_motor, 8u, 0xffu);
    fr_temp_inverter = (uint16_t)src_p->fr_temp_inverter;
    dst_p[2] |= pack_left_shift_u16(fr_temp_inverter, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(fr_temp_inverter, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->fr_error_info, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->fr_error_info, 8u, 0xffu);
    fr_temp_igbt = (uint16_t)src_p->fr_temp_igbt;
    dst_p[6] |= pack_left_shift_u16(fr_temp_igbt, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fr_temp_igbt, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fr_amk_actual_2_unpack(
    struct inverter_dbc_fr_amk_actual_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fr_temp_igbt;
    uint16_t fr_temp_inverter;
    uint16_t fr_temp_motor;

    if (size < 8u) {
        return (-EINVAL);
    }

    fr_temp_motor = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    fr_temp_motor |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->fr_temp_motor = (int16_t)fr_temp_motor;
    fr_temp_inverter = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    fr_temp_inverter |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fr_temp_inverter = (int16_t)fr_temp_inverter;
    dst_p->fr_error_info = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->fr_error_info |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    fr_temp_igbt = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fr_temp_igbt |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fr_temp_igbt = (int16_t)fr_temp_igbt;

    return (0);
}

int inverter_dbc_fr_amk_actual_2_init(struct inverter_dbc_fr_amk_actual_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fr_amk_actual_2_t));

    return 0;
}

int16_t inverter_dbc_fr_amk_actual_2_fr_temp_motor_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fr_amk_actual_2_fr_temp_motor_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fr_amk_actual_2_fr_temp_motor_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t inverter_dbc_fr_amk_actual_2_fr_temp_inverter_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fr_amk_actual_2_fr_temp_inverter_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fr_amk_actual_2_fr_temp_inverter_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t inverter_dbc_fr_amk_actual_2_fr_error_info_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_fr_amk_actual_2_fr_error_info_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_actual_2_fr_error_info_is_in_range(uint16_t value)
{
    return (value <= 3277u);
}

int16_t inverter_dbc_fr_amk_actual_2_fr_temp_igbt_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fr_amk_actual_2_fr_temp_igbt_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fr_amk_actual_2_fr_temp_igbt_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int inverter_dbc_fr_amk_rit_set1_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fr_amk_rit_set1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->fr_errorlist1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->fr_errorlist1, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->fr_errorlist1, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->fr_errorlist1, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->fr_errorlist2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->fr_errorlist2, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->fr_errorlist2, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->fr_errorlist2, 24u, 0xffu);

    return (8);
}

int inverter_dbc_fr_amk_rit_set1_unpack(
    struct inverter_dbc_fr_amk_rit_set1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fr_errorlist1 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->fr_errorlist1 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->fr_errorlist1 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->fr_errorlist1 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->fr_errorlist2 = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->fr_errorlist2 |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->fr_errorlist2 |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->fr_errorlist2 |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int inverter_dbc_fr_amk_rit_set1_init(struct inverter_dbc_fr_amk_rit_set1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fr_amk_rit_set1_t));

    return 0;
}

uint32_t inverter_dbc_fr_amk_rit_set1_fr_errorlist1_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_fr_amk_rit_set1_fr_errorlist1_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_rit_set1_fr_errorlist1_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint32_t inverter_dbc_fr_amk_rit_set1_fr_errorlist2_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_fr_amk_rit_set1_fr_errorlist2_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_rit_set1_fr_errorlist2_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

int inverter_dbc_fr_amk_rit_set2_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fr_amk_rit_set2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->fr_errorlist3, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->fr_errorlist3, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->fr_errorlist3, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->fr_errorlist3, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->fr_dc_bus_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->fr_dc_bus_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->fr_dc_bus_voltage_monitoring, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->fr_dc_bus_voltage_monitoring, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fr_amk_rit_set2_unpack(
    struct inverter_dbc_fr_amk_rit_set2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fr_errorlist3 = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->fr_errorlist3 |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->fr_errorlist3 |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->fr_errorlist3 |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->fr_dc_bus_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->fr_dc_bus_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fr_dc_bus_voltage_monitoring = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->fr_dc_bus_voltage_monitoring |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int inverter_dbc_fr_amk_rit_set2_init(struct inverter_dbc_fr_amk_rit_set2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fr_amk_rit_set2_t));

    return 0;
}

uint32_t inverter_dbc_fr_amk_rit_set2_fr_errorlist3_encode(double value)
{
    return (uint32_t)(value);
}

double inverter_dbc_fr_amk_rit_set2_fr_errorlist3_decode(uint32_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_rit_set2_fr_errorlist3_is_in_range(uint32_t value)
{
    return (value <= 1u);
}

uint16_t inverter_dbc_fr_amk_rit_set2_fr_dc_bus_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double inverter_dbc_fr_amk_rit_set2_fr_dc_bus_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_rit_set2_fr_dc_bus_voltage_is_in_range(uint16_t value)
{
    return (value <= 4096u);
}

uint16_t inverter_dbc_fr_amk_rit_set2_fr_dc_bus_voltage_monitoring_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double inverter_dbc_fr_amk_rit_set2_fr_dc_bus_voltage_monitoring_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fr_amk_rit_set2_fr_dc_bus_voltage_monitoring_is_in_range(uint16_t value)
{
    return (value <= 40960u);
}

int inverter_dbc_fr_amk_setpoints_pack(
    uint8_t *dst_p,
    const struct inverter_dbc_fr_amk_setpoints_t *src_p,
    size_t size)
{
    uint16_t fr_amk_torque_limit_negative;
    uint16_t fr_amk_torque_limit_positive;
    uint16_t fr_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->fr_amk_b_inverter_on, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_amk_b_dc_on, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_amk_b_enable, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->fr_amk_b_error_reset, 3u, 0x08u);
    fr_amk_torque_setpoint = (uint16_t)src_p->fr_amk_torque_setpoint;
    dst_p[2] |= pack_left_shift_u16(fr_amk_torque_setpoint, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(fr_amk_torque_setpoint, 8u, 0xffu);
    fr_amk_torque_limit_positive = (uint16_t)src_p->fr_amk_torque_limit_positive;
    dst_p[4] |= pack_left_shift_u16(fr_amk_torque_limit_positive, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(fr_amk_torque_limit_positive, 8u, 0xffu);
    fr_amk_torque_limit_negative = (uint16_t)src_p->fr_amk_torque_limit_negative;
    dst_p[6] |= pack_left_shift_u16(fr_amk_torque_limit_negative, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(fr_amk_torque_limit_negative, 8u, 0xffu);

    return (8);
}

int inverter_dbc_fr_amk_setpoints_unpack(
    struct inverter_dbc_fr_amk_setpoints_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t fr_amk_torque_limit_negative;
    uint16_t fr_amk_torque_limit_positive;
    uint16_t fr_amk_torque_setpoint;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fr_amk_b_inverter_on = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->fr_amk_b_dc_on = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->fr_amk_b_enable = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->fr_amk_b_error_reset = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    fr_amk_torque_setpoint = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    fr_amk_torque_setpoint |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fr_amk_torque_setpoint = (int16_t)fr_amk_torque_setpoint;
    fr_amk_torque_limit_positive = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    fr_amk_torque_limit_positive |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fr_amk_torque_limit_positive = (int16_t)fr_amk_torque_limit_positive;
    fr_amk_torque_limit_negative = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    fr_amk_torque_limit_negative |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->fr_amk_torque_limit_negative = (int16_t)fr_amk_torque_limit_negative;

    return (0);
}

int inverter_dbc_fr_amk_setpoints_init(struct inverter_dbc_fr_amk_setpoints_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct inverter_dbc_fr_amk_setpoints_t));

    return 0;
}

uint8_t inverter_dbc_fr_amk_setpoints_fr_amk_b_inverter_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_setpoints_fr_amk_b_inverter_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_setpoints_fr_amk_b_inverter_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_setpoints_fr_amk_b_dc_on_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_setpoints_fr_amk_b_dc_on_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_setpoints_fr_amk_b_dc_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_setpoints_fr_amk_b_enable_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_setpoints_fr_amk_b_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_setpoints_fr_amk_b_enable_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t inverter_dbc_fr_amk_setpoints_fr_amk_b_error_reset_encode(double value)
{
    return (uint8_t)(value);
}

double inverter_dbc_fr_amk_setpoints_fr_amk_b_error_reset_decode(uint8_t value)
{
    return ((double)value);
}

bool inverter_dbc_fr_amk_setpoints_fr_amk_b_error_reset_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t inverter_dbc_fr_amk_setpoints_fr_amk_torque_setpoint_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fr_amk_setpoints_fr_amk_torque_setpoint_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fr_amk_setpoints_fr_amk_torque_setpoint_is_in_range(int16_t value)
{
    return ((value >= -10000) && (value <= 10000));
}

int16_t inverter_dbc_fr_amk_setpoints_fr_amk_torque_limit_positive_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fr_amk_setpoints_fr_amk_torque_limit_positive_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fr_amk_setpoints_fr_amk_torque_limit_positive_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}

int16_t inverter_dbc_fr_amk_setpoints_fr_amk_torque_limit_negative_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double inverter_dbc_fr_amk_setpoints_fr_amk_torque_limit_negative_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool inverter_dbc_fr_amk_setpoints_fr_amk_torque_limit_negative_is_in_range(int16_t value)
{
    return ((value >= -30000) && (value <= 30000));
}
